Repository Grusie/SharingMap, pull requests merged in 2024-09, with the labels that each got.

#20 Feat/#2 네이버 맵 기술검토
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grusie/sharingmap/data/MarkerItem.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/MainActivity.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/map/MapScreen.kt
  app/src/main/java/com/grusie/sharingmap/ui/navigation/main/SharingMapApplication.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 👍feature

#22 feat: 검색 스크린 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grusie/sharingmap/data/FakeSearch.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/Comment.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/CustomTab.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/CustomTextField.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/User.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/theme/Type.kt
  app/src/main/java/com/grusie/sharingmap/ui/application/SharingMap.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/home/FeedModal.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/home/HomeScreen.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/home/HomeUiState.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/search/SearchContent.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/search/SearchScreen.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/search/SearchUiState.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/grusie/sharingmap/ui/mapper/SearchMapper.kt
  app/src/main/java/com/grusie/sharingmap/ui/model/SearchTab.kt
  app/src/main/java/com/grusie/sharingmap/ui/model/TagUiModel.kt
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  data/src/androidTest/java/com/grusie/data/ExampleInstrumentedTest.kt
  data/src/main/java/com/gruise/data/dao/TagSearchDao.kt
  data/src/main/java/com/gruise/data/dao/UserSearchDao.kt
  data/src/main/java/com/gruise/data/database/TagSearchDatabase.kt
  data/src/main/java/com/gruise/data/database/UserSearchDatabase.kt
  data/src/main/java/com/gruise/data/datasource/SearchDataSource.kt
  data/src/main/java/com/gruise/data/datasource/SearchRemoteDataSource.kt
  data/src/main/java/com/gruise/data/di/DataSourceModule.kt
  data/src/main/java/com/gruise/data/di/DatabaseModule.kt
  data/src/main/java/com/gruise/data/di/RepositoryModule.kt
  data/src/main/java/com/gruise/data/di/UseCaseModule.kt
  data/src/main/java/com/gruise/data/mapper/SearchMapper.kt
  data/src/main/java/com/gruise/data/model/LocalTagSearch.kt
  data/src/main/java/com/gruise/data/model/LocalUserSearch.kt
  data/src/main/java/com/gruise/data/repository/DefaultSearchRepository.kt
  data/src/test/java/com/grusie/data/ExampleUnitTest.kt
  domain/build.gradle.kts
  domain/src/main/java/com/gruise/domain/model/TagSearch.kt
  domain/src/main/java/com/gruise/domain/model/UserSearch.kt
  domain/src/main/java/com/gruise/domain/repository/SearchRepository.kt
  domain/src/main/java/com/gruise/domain/usecase/search/DeleteAllTagSearchUseCase.kt
  domain/src/main/java/com/gruise/domain/usecase/search/DeleteAllUserSearchUseCase.kt
  domain/src/main/java/com/gruise/domain/usecase/search/GetAllTagSearchUseCase.kt
  domain/src/main/java/com/gruise/domain/usecase/search/GetAllUserSearchUseCase.kt
  domain/src/main/java/com/gruise/domain/usecase/search/InsertTagSearchUseCase.kt
  domain/src/main/java/com/gruise/domain/usecase/search/InsertUserSearchUseCase.kt
  domain/src/main/java/com/gruise/domain/usecase/search/SearchUseCase.kt
  gradle/libs.versions.toml
Labels: 👍feature

#24 fix: Application 파일이 겹처서 생기는 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/grusie/sharingmap/ui/navigation/main/SharingMapApplication.kt
Labels: 🐞bug

#25 feat: 마이페이지 컴포넌트 구현
  app/src/main/java/com/grusie/sharingmap/designsystem/component/CustomButton.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/CustomTextField.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/LimitedText.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/User.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/theme/Color.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/MyPageUserInfo.kt
  app/src/main/java/com/grusie/sharingmap/ui/model/UserUiModel.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/values/strings.xml
Labels: 👍feature

#29 feat: 마이페이지 스크린 구현
  app/src/main/java/com/grusie/sharingmap/data/Const.kt
  app/src/main/java/com/grusie/sharingmap/data/FakeStorage.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/Comment.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/CustomBottomSheet.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/CustomButton.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/CustomTextField.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/ModalItem.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/theme/Color.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/MainActivity.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/MyPageScreen.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/MyPageUiState.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/StorageContent.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/storage/StorageScreen.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/storage/StorageUiState.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/storage/StorageViewModel.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/search/SearchContent.kt
  app/src/main/java/com/grusie/sharingmap/ui/model/MyPageTab.kt
  app/src/main/java/com/grusie/sharingmap/ui/model/StorageUiModel.kt
  app/src/main/java/com/grusie/sharingmap/ui/navigation/main/MainBottomNavGraph.kt
  app/src/main/java/com/grusie/sharingmap/ui/navigation/main/NavItem.kt
  app/src/main/res/drawable/btn_back.xml
  app/src/main/res/drawable/btn_lock.xml
  app/src/main/res/drawable/btn_setting.xml
  app/src/main/res/drawable/btn_unlock.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/values/strings.xml
Labels: 👍feature

#30 refactor: 상태바수정
  app/src/main/java/com/grusie/sharingmap/designsystem/component/CustomTab.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/theme/Theme.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/MainActivity.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/home/HomeScreen.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/MyPageScreen.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/mypage/storage/StorageScreen.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/search/SearchScreen.kt
Labels: 🛠refactor

#31 refactor: 검색 스크린 수정
  app/src/main/java/com/grusie/sharingmap/ui/main/MainActivity.kt
  app/src/main/java/com/grusie/sharingmap/ui/main/search/SearchScreen.kt
  app/src/main/java/com/grusie/sharingmap/ui/navigation/main/MainBottomNavGraph.kt
Labels: 👍feature, 🛠refactor

#34 feat: 더보기, 접기 추가해서 클릭시 확장 및 축소가 가능하도록 기능 구현
  app/src/main/java/com/grusie/sharingmap/designsystem/component/LimitedText.kt
  app/src/main/java/com/grusie/sharingmap/designsystem/component/User.kt
Labels: 👍feature, 🛠refactor

#39 feat: 서버작업 구현
  data/build.gradle.kts
  data/src/main/java/com/gruise/data/di/RetrofitModule.kt
  data/src/main/java/com/gruise/data/remote/FetchState.kt
  data/src/main/java/com/gruise/data/remote/PlaceCokCall.kt
  data/src/main/java/com/gruise/data/remote/PlaceCokCallAdapter.kt
  data/src/main/java/com/gruise/data/remote/PlaceCokCallAdapterFactory.kt
  data/src/main/java/com/gruise/data/remote/RemoteError.kt
  data/src/main/java/com/gruise/data/service/client/AccessTokenInterceptor.kt
  gradle/libs.versions.toml
Labels: 👍feature
